### ISSUE TITLE
Dataset Preprocess

### ISSUE THREAD

**Issue by gamesdsad** [erprogs/GenConViT#11]
First of all thank you for sharing your project. What happens to data preprocessing when I want to train a new model with FF++ and DFDC data?

**Comment by erprogs** [comment]
Hi,
extract the images from the dataset, and store it in [sample train data](https://github.com/erprogs/GenConViT/tree/main/sample_train_data) format.

**Comment by gamesdsad** [comment]
> Hi, extract the images from the dataset, and store it in [sample train data](https://github.com/erprogs/GenConViT/tree/main/sample_train_data) format.

Thank you for your quick reply, I have a general understanding of the principle, you are referring to the FF++ and DFDC preprocessing, detection of face extraction frame, and frame data is divided into the [sample_train_data](https://github.com/erprogs/GenConViT/tree/main/sample_train_data) format?

**Comment by erprogs** [comment]
For training the model, yes, during inference, you don't need that format. You just extract face regions from video frames and pass them to the model.

**Comment by gamesdsad** [comment]
I know what your mean.Thank you very much!!!!
> For training the model, yes, during inference, you don't need that format. You just extract face regions from video frames and pass them to the model.
