### ISSUE TITLE
Processed Dataset

### ISSUE THREAD

**Issue by guishengzhanga** [erprogs/GenConViT#3]
Hi, I am very interested in the 'Deepfake Video Detection Using Generative Convolutional Vision Transformer' research. Could you please provide the processed dataset? Thank you very much!!!

**Comment by erprogs** [comment]
Hello, thank you for your interest in our deepfake research. To create the dataset, I wrote some custom code to extract frames from the DFDC, FF, Celeb dataset. Here is the [CViT faceextract](https://github.com/erprogs/CViT/tree/main/preprocessing)  custom code for extracting the DFDC dataset. I used it in the CViT paper. 

I used the same code to extract data from FF and DeepFake-TIMIT with minor logic change. The only difference is that I used a numbering mechanism to balance the ratio between fake and real videos.

e.g. for FF, I used the first 900 for training, 100 for validation, the rest to testing (_something like that_). I used similar mechanism for the rest of the dataset. 

I do not have permission to redistribute those datasets and their derivatives directly. However, I can provide you with the Json list of the images extracted from the videos. 

Tip: there is an extracted face dataset that you can download from the dfdc kaggle website. 

I hope I've answered your question.

**Comment by guishengzhanga** [comment]
Thanks for your response, it's very helpful to me.

**Comment by erprogs** [comment]
Great!

**Comment by guishengzhanga** [comment]
Thanks very much! Would you be able to share with me the JSON list of images extracted from the videos?

**Comment by erprogs** [comment]
[deepfake_json.zip](https://github.com/erprogs/GenConViT/files/13624164/deepfake_json.zip)
