### ISSUE TITLE
The trained model cannot be used for prediction

### ISSUE THREAD

**Issue by HioZx** [erprogs/GenConViT#4]
I used training scripts to get my VAE model: `python train.py --d sample_train_data --m vae -e 5 -t y`

Then I changed the path of the vae model in pred-func.py, but using the predicted script gave me an error：Missing key(s) in state_dict and  Unexpected key(s).The structure of the two models is inconsistent.
I also found that the model size of the saved VAE was not consistent with the pre-trained model size you provided. The model size of my trained VAE became twice as large, about 5G in size.
I sincerely hope that you can help me, how to use their own trained model for inference.

**Comment by YuqiHuang7** [comment]
How do you solve this problem? I have encountered the same one.

**Comment by erprogs** [comment]
Hello @HioZx  and @YuqiHuang7, sorry for the inconvenience.

I have made a new update to the repo, and the update fixes some issues you may have encountered. can you update your repo again to check if the problem goes away? Thanks. 
After the update, you can run the following: (check the read me for more info)


**Example usage:** 
```bash
python prediction.py --p DeepfakeTIMIT --d timit --f 10 
```
To use VAE or ED variant:

VAE:
``` 
python prediction.py --p sample_prediction_data --v --f 10
```

ED:
```
python prediction.py --p sample_prediction_data --e --f 10
```

VAE test on DeepfakeTIMIT dataset:
```
python prediction.py --p DeepfakeTIMIT --v --d timit --f 10
```
run VAE and ED (GENCONVIT): *this runs the provided weights as a defualt*

```
python prediction.py --p sample_prediction_data --e --v --f 10
```

**Testing a new model:**


If you have trained a new model (e.g., if we have `weight/genconvit_vae_May_16_2024_09_34_21.pth`) and want to test it, use the following:

VAE:
```
python prediction.py --p sample_prediction_data --v genconvit_vae_May_16_2024_09_34_21 --f 10
```

ED:
```
python prediction.py --p sample_prediction_data --e genconvit_ed_May_16_2024_10_18_09 --f 10
```

BOTH VAE and ED (GENCONVIT):

```
python prediction.py --p sample_prediction_data --e genconvit_ed_May_16_2024_10_18_09 --v genconvit_vae_May_16_2024_09_34_21 --f 10
```

**Comment by YuqiHuang7** [comment]
I have changed the repo,and it works well. Thanks so much!!!
